Django_By_Example_Code/Chapter 3/mysite/blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed


urlpatterns = [
    # post views,< >内是传入的参数, views.py设置views, name在models=>get_absolute_url中用到
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
]

Django_By_Example_Code/Chapter 3/mysite/mysite/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

#设置sitemaps
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)), #admin的url
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')), #包含blog.urls
    url(r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'), #sitemap的url
]

Django_By_Example_Code/Chapter 3/mysite/blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        #重新定义get_queryset,筛选published的对象
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    #草稿和已发布
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish') #SlugField和unique_for_date的用法
    author = models.ForeignKey(User, related_name='blog_posts') #ForeignKey和related_name的用法
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True) #auto_now_add的用法,和auto_now的区别
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft') #CharField和choices的用法

    objects = models.Manager() # The default manager.
    published = PublishedManager() # PublishedManager的用法

    tags = TaggableManager() #TaggableManager的用法

    class Meta:
        ordering = ('-publish',) #ordering的用法,-表示倒序

    def __str__(self):
        return self.title #__str__的用法

    def get_absolute_url(self): #get_absolute_url和reverse的用法
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments') #ForeignKey和related_name的用法
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',) #ordering的用法

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post) #__str__的用法

Django_By_Example_Code/Chapter 3/mysite/blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Comment


class EmailPostForm(forms.Form): #forms.Form的用法
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body') #ModleForm, Meta和fields的用法


class SearchForm(forms.Form):
    query = forms.CharField() #search.html中有 if "query" in request.GET

Django_By_Example_Code/Chapter 3/mysite/blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from haystack.query import SearchQuerySet


def post_list(request, tag_slug=None):
    #Post清单
    object_list = Post.published.all()
    tag = None

    #如果有tag_slug,tag_slug=>tag=>object_list
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    #分页
    paginator = Paginator(object_list, 3) # 每页3篇文章
    #request.GET的用法,Paginator生成'page'
    page = request.GET.get('page')
    try:
        #当前页面的posts
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果page不是整数,显示第一页
        posts = paginator.page(1)
    except EmptyPage:
        # 如果page太大,给出最后一页
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag}) #render的用法


#django的ListView的用法,是对post_list的简化
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    # 从Post的slug,publish属性获得当前文章
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # 当前文章的所有评论
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # 从表单获取评论
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # 创建评论对象,但不提交保存
            new_comment = comment_form.save(commit=False)
            # 指定当前评论到当前文章
            new_comment.post = post
            # 保存评论到数据库
            new_comment.save()
    else:
        comment_form = CommentForm()

    # 相似的文章清单
    post_tags_ids = post.tags.values_list('id', flat=True) #values_list的用法
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id) #filter和exclude的用法
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4] #annotate的用法,same_tags是相同tags的数量
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts}) #render的用法



def post_share(request, post_id):
    # 通过id获取文章
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # 提交了表单
        form = EmailPostForm(request.POST) #EmailPostForm来自blog/forms.py
        if form.is_valid():
            # 表单内容通过验证
            cd = form.cleaned_data #cleaned_data的用法
            post_url = request.build_absolute_uri(post.get_absolute_url()) #build_absolute_uri的用法
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title) #format和cd的用法
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments']) #format和cd的用法
            send_mail(subject, message, 'admin@myblog.com', [cd['to']]) #send_mail的用法
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    # request.GET的用法
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all() #SearchQuerySet的用法
            # 对所有结果计数
            total_results = results.count()
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'cd': cd,
                                                     'results': results,
                                                     'total_results': total_results})

Django_By_Example_Code/Chapter 3/mysite/blog/templates/blog/post/detail.html
<!--extends的用法-->
{% extends "blog/base.html" %}
<!--blog_tags.py中的total_posts, show_latest_posts, get_most_commented_posts生效-->
{% load blog_tags %}

<!--title的用法-->
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <!--views.py中post_detail给出post-->
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    <!--blog_tags给出markdown-->
    {{ post.body|markdown }}
    <!--blog/urls.py中post_share给出blog:post_share-->
    <p><a href="{% url "blog:post_share" post.id %}">Share this post</a></p>
    
    <h2>Similar posts</h2>
    <!--blog/views.py中post_detail给出similar_posts-->
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    <!--similar_posts为空时,empty部分生效-->
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    <!--comments数量-->
    {% with comments.count as total_comments %}
        <!--pluralize显示total_comments-->
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}

    <!--forloop.counter表示第几条评论,linebreaks显示comment.body-->
    {% for comment in comments %}
        <div class="comment">
            <p class="info">Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            {{ comment.body|linebreaks }}
        </div>
    <!--comments为空时,empty部分生效-->
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    <!--提交评论后-->
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
    <!--提交评论的表单-->
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {%  endif %}
{% endblock %}

Django_By_Example_Code/Chapter 3/mysite/blog/templates/blog/post/latest_posts.html
<!--templatetags/blog_tags.py中用到-->
<ul>
{% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>

Django_By_Example_Code/Chapter 3/mysite/blog/templates/blog/post/list.html
<!--extends的用法-->
{% extends "blog/base.html" %}
<!--blog_tags.py中的total_posts, show_latest_posts, get_most_commented_posts生效-->
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    <!--如果有tag,显示tag name-->
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    <!--每个post-->
    {% for post in posts %}
        <!--显示post.title,href是post的detail-->
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="tags">
            Tags:
            <!--显示post.tags的tag name-->
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                <!--如果不是最后一个,添加逗号-->
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <!--时间和作者-->
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        <!--markdown显示正文,正文显示30个字符-->
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    <!--传递posts到page-->
    {% include "pagination.html" with page=posts %}
{% endblock %}

Django_By_Example_Code/Chapter 3/mysite/blog/templates/blog/post/search.html
<!--extends的用法-->
{% extends "blog/base.html" %}

<!--title的用法-->
{% block title %}Search{% endblock %}

{% block content %}
    <!--request.GET的用法-->
    {% if "query" in request.GET %}
        <!--cd的用法-->
        <h1>Posts containing "{{ cd.query }}"</h1>
        <!--pluralize的用法-->
        <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
        {% for result in results %}
        	{% with post=result.object %}
        		<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
        	{% endwith %}
        {% empty %}
        	<p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <!--request.method的用法-->
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

Django_By_Example_Code/Chapter 3/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    <!--已经发送-->
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent by e-mail.</p>
    {% else %}
        <!--提交发送的表单-->
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            <!--设置csrf-->
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}